import { useState, useRef, useEffect } from 'react';
import { askDoubtBuster } from '../lib/aiService';
import { Sparkles, X, Download, RotateCcw, Plus } from 'lucide-react';
import {
  RATE_LIMIT, SUPABASE_URL, SUPABASE_ANON_KEY, SYSTEM_PROMPT,
  getRateLimitData, checkAndIncrementRateLimit,
} from './chatbot/chatbotConstants';
import ChatPanel from './chatbot/ChatPanel';
import DoubtBusterPanel from './chatbot/DoubtBusterPanel';
import './chatbot/chatbot.css';

export default function ChatBot({ chatBotMode = null, setChatBotMode }) {
  const [open, setOpen]             = useState(false);
  const [mode, setMode]             = useState('chat');
  const [messages, setMessages]     = useState([]);
  const [input, setInput]           = useState('');
  const [loading, setLoading]       = useState(false);
  const [error, setError]           = useState('');
  const [doubtInput, setDoubtInput] = useState('');
  const [doubtResult, setDoubtResult] = useState({ loading: false, text: null, error: null });
  const [notesDownloading, setNotesDownloading] = useState(false);
  const messagesEndRef = useRef(null);
  const inputRef = useRef(null);

  useEffect(() => {
    if (open) {
      messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' });
      setTimeout(() => inputRef.current?.focus(), 100);
    }
  }, [messages, open]);

  useEffect(() => {
    if (!chatBotMode) return;
    setOpen(true);
    setMode(chatBotMode);
    if (setChatBotMode) setChatBotMode(null);
  }, [chatBotMode]); // eslint-disable-line react-hooks/exhaustive-deps

  useEffect(() => {
    document.body.style.overflow = open ? 'hidden' : '';
    return () => { document.body.style.overflow = ''; };
  }, [open]);

  const sendMessage = async (text) => {
    const textToSend = (text || input).trim();
    if (!textToSend || loading) return;

    const rl = checkAndIncrementRateLimit();
    if (!rl.allowed) {
      setError('Daily limit of 20 questions reached. Try again tomorrow.');
      return;
    }

    setInput('');
    setError('');
    const userMsg = { role: 'user', content: textToSend };
    const newMessages = [...messages, userMsg];
    setMessages(newMessages);
    setLoading(true);

    try {
      const response = await fetch(`${SUPABASE_URL}/functions/v1/gemini-proxy`, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'Authorization': `Bearer ${SUPABASE_ANON_KEY}`,
        },
        body: JSON.stringify({
          system: SYSTEM_PROMPT,
          messages: newMessages.map(m => ({ role: m.role, content: m.content })),
        }),
      });

      if (!response.ok) {
        const err = await response.json().catch(() => ({}));
        throw new Error(err.error || `API error ${response.status}`);
      }

      const data = await response.json();
      const assistantText = data.text || 'Sorry, I couldn\'t generate a response.';
      setMessages(prev => [...prev, { role: 'assistant', content: assistantText }]);
    } catch (err) {
      setMessages(prev => [...prev, { role: 'assistant', content: `⚠️ ${err.message || 'Request failed. Please try again.'}` }]);
    } finally {
      setLoading(false);
    }
  };

  const handleDoubtBuster = async () => {
    const q = doubtInput.trim();
    if (!q || doubtResult.loading) return;
    setDoubtResult({ loading: true, text: null, error: null });
    const { text, error } = await askDoubtBuster(q);
    setDoubtResult({ loading: false, text, error });
  };

  const newChat = () => {
    setMessages([]);
    setInput('');
    setError('');
    setTimeout(() => inputRef.current?.focus(), 100);
  };

  const downloadAsNotes = async () => {
    if (messages.length === 0) return;
    setNotesDownloading(true);

    const firstUserMsg = messages.find(m => m.role === 'user')?.content || 'iConnect Session';
    const topicRaw = firstUserMsg.slice(0, 60).replace(/[^a-zA-Z0-9 ]/g, '').trim();
    const filename  = (topicRaw || 'iConnect Notes').replace(/\s+/g, '_') + '.md';
    const dateStr   = new Date().toLocaleDateString('en-IN', { day: 'numeric', month: 'long', year: 'numeric' });

    try {
      const lines = [];
      lines.push(`# 📚 ${topicRaw || 'Study Notes'}`);
      lines.push(`*Generated by iConnect AI Assistant · ${dateStr}*`);
      lines.push('');
      lines.push('---');
      lines.push('');

      let noteIndex = 1;
      for (const msg of messages) {
        if (msg.role === 'user') {
          lines.push(`## 🔹 Topic ${noteIndex}: ${msg.content.slice(0, 80)}${msg.content.length > 80 ? '…' : ''}`);
          lines.push('');
          noteIndex++;
        } else {
          const formatted = msg.content.replace(/^[-•]\s+/gm, '- ').replace(/\*\*/g, '**');
          lines.push(formatted);
          lines.push('');
          lines.push('---');
          lines.push('');
        }
      }

      lines.push('');
      lines.push('*These notes were compiled from your iConnect AI Assistant conversation.*');
      lines.push('*For clinical decisions, always consult a qualified physician.*');

      const blob = new Blob([lines.join('\n')], { type: 'text/markdown;charset=utf-8' });
      const url  = URL.createObjectURL(blob);
      const a    = document.createElement('a');
      a.href = url; a.download = filename;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);
    } catch (_) {}

    setNotesDownloading(false);
  };

  const { count: todayCount } = getRateLimitData();
  const remaining = RATE_LIMIT - (todayCount || 0);
  const hasMessages = messages.length > 0;

  return (
    <>
      <button onClick={() => setOpen(o => !o)} className="chatbot-fab" title="iConnect AI Assistant">
        {open ? <X size={20} /> : <Sparkles size={22} />}
      </button>

      {open && <div className="chatbot-backdrop" onClick={() => setOpen(false)} />}

      <div className={`chatbot-drawer ${open ? 'chatbot-drawer-open' : ''}`}>

        {/* Header */}
        <div className="chatbot-header">
          <div className="chatbot-header-icon"><Sparkles size={18} /></div>
          <div className="chatbot-header-text">
            <div className="chatbot-header-title">iConnect Assistant</div>
            <div className="chatbot-header-sub">AI-powered academic guidance</div>
          </div>
          <div style={{ display: 'flex', alignItems: 'center', gap: 4, marginLeft: 'auto' }}>
            <button className="chatbot-action-btn" onClick={newChat} title="New conversation">
              <Plus size={15} />
            </button>
            {hasMessages && (
              <button className="chatbot-action-btn" onClick={downloadAsNotes} disabled={notesDownloading} title="Download as notes">
                {notesDownloading ? <span style={{ fontSize: 11 }}>⏳</span> : <Download size={15} />}
              </button>
            )}
            <button className="chatbot-close-btn" onClick={() => setOpen(false)}>
              <X size={18} />
            </button>
          </div>
        </div>

        {/* Mode Tabs */}
        <div className="chatbot-tabs">
          {[['chat', '💬 Chat'], ['doubt', '🧠 Doubt Buster']].map(([k, l]) => (
            <button key={k} onClick={() => setMode(k)} className={`chatbot-tab ${mode === k ? 'active' : ''}`}>
              {l}
            </button>
          ))}
        </div>

        {mode === 'chat' && (
          <ChatPanel
            messages={messages}
            loading={loading}
            error={error}
            input={input}
            setInput={setInput}
            onSend={sendMessage}
            remaining={remaining}
          />
        )}

        {mode === 'doubt' && (
          <DoubtBusterPanel
            doubtInput={doubtInput}
            setDoubtInput={setDoubtInput}
            doubtResult={doubtResult}
            onSubmit={handleDoubtBuster}
            onReset={() => { setDoubtResult({ loading: false, text: null, error: null }); setDoubtInput(''); }}
          />
        )}
      </div>
    </>
  );
}
